### ISSUE TITLE
When I put more than 3 datasets into the K8s, it ends up with an error

### ISSUE THREAD

**Issue by zoneout215** [abelsiqueira/asreview-cloud#4]
When I put more than 3 datasets into the K8s, it ends up with an error

**To Reproduce**
I followed README.md with 4 datasets from Synergy-datasets  in the `data` folder: van den Schoot, Lenaars, Hall, and Menon. 
This leads to errors in all of the workers:

Received 'asreview simulate data/Hall_2012.csv -s output/simulation/Hall_2012/state_files/sim_Hall_2012_4905.asreview --prior_record_id 4905 231 5214 36 4214 788 8582 7303 3880 4806 7253 --seed 165\n'
Traceback (most recent call last):
  File "/root/.local/bin/asreview", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/asreview/__main__.py", line 48, in main
    entry.load()().execute(sys.argv[2:])
  File "/root/.local/lib/python3.8/site-packages/asreview/entry_points/simulate.py", line 137, in execute
    raise ProjectExistsError("Project already exists.")
asreview.project.ProjectExistsError: Project already exists.
Traceback (most recent call last):
  File "/app/worker-receiver.py", line 53, in <module>
    worker = Worker()
  File "/app/worker-receiver.py", line 37, in __init__
    channel.start_consuming()
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "/app/worker-receiver.py", line 41, in callback
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'asreview simulate data/Hall_2012.csv -s output/simulation/Hall_2012/state_files/sim_Hall_2012_4905.asreview --prior_record_id 4905 231 5214 36 4214 788 8582 7303 3880 4806 7253 --seed 165 

**Additional information**
 - OS: Mac M1
 - ASReview version ..2
 - CPU limit in `worker.yml` is 500 
 - Memory limit in `worker.yml` is 552

**Comment by abelsiqueira** [comment]
Something happened before this error that led to the workers breaking down and leaving behind a .asreview file. You will have to run again but keep the `kubectl logs asreview-worker-... -f` open to see the actual error message. We will have to log to file to avoid this. I **think** it is because of running a long time without response. Try increasing the CPU to 1000 and memory to 2048 as well, because it might be necessary.

Also, you should use the `examples/custom_arfi_synergy` template (and the `sed` command in `tasker.sh`) to delete the `.asreview` after use, because they will fill up the disk.

**Comment by abelsiqueira** [comment]
This was fixed.
